# Generated by Django 5.1.7 on 2025-06-23 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subscribers',
            new_name='profile_subscribers',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='video',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_subscribers',
            field=models.ManyToManyField(blank=True, related_name='user_subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='video_subscribers',
            field=models.ManyToManyField(blank=True, related_name='video_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
