# Generated by Django 5.1.7 on 2025-06-23 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_subscribers_profile_profile_subscribers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_subscribers',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
